### ISSUE TITLE
Return English language (text) Default 

### ISSUE THREAD

**Issue by Xapitonov** [jan-mate/Journalize#2]
Does not translate to the bottom button bar
Render/Edit

Russian language (text)
~Вид/Код~
Обзор/Текст

![Screenshot_2024-09-25-23-23-56-447_com.example.journal.jpg](https://github.com/user-attachments/assets/0467f091-e55c-4748-8536-6506cbd08502)

![Screenshot_2024-09-25-23-24-12-628_com.example.journal.jpg](https://github.com/user-attachments/assets/ee0f270d-a625-4d41-a9d1-9b13cb20f3e3)

![Screenshot_2024-09-25-23-24-29-979_com.example.journal.jpg](https://github.com/user-attachments/assets/a339ddb4-cfd1-4473-a6fe-b8fc14c7f3db)

**Comment by jan-mate** [comment]
I didn't expect people would translate the app, so I did a lot of hardcoding, sry :/ 
I might make the app translatable in future.
For now, if you want a quick fix to make your fork work with russian, you can change 2 lines in app/src/main/java/com/example/journal/MarkdownUtils.kt , simply change the "Edit" and "Render" to your russian translation

```kotlin
fun toggleRenderMode(context: Context, isEditMode: Boolean, editText: EditText, renderedTextView: TextView, renderButton: Button): Boolean {
        return if (isEditMode) {
            renderMarkdown(context, editText.text.toString(), renderedTextView)
            renderButton.text = "Edit" // Change this
            editText.visibility = View.GONE
            renderedTextView.visibility = View.VISIBLE
            KeyboardUtils.hideKeyboard(context, renderButton)
            false
        } else {
            editText.visibility = View.VISIBLE
            renderedTextView.visibility = View.GONE
            renderButton.text = "Render" // Change this
            KeyboardUtils.showKeyboard(context, editText)
            true
        }
    }
```

**Comment by Xapitonov** [comment]
ОК 🤝

чт, 26 сент. 2024 г., 17:49 jan-mate ***@***.***>:
